<Project Sdk="Microsoft.NET.Sdk">
    <!-- NuGet references -->
    <ItemGroup>
        <PackageReference Include="NLog"/>
        <PackageReference Include="Krafs.Rimworld.Ref"/>
        <PackageReference Include="com.sirrandoo.twitchtoolkit.ref"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../ToolkitUtils.Api/ToolkitUtils.Api.csproj"/>
        <ProjectReference Include="../ToolkitUtils.Core/ToolkitUtils.Core.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Microsoft.Extensions.DependencyInjection">
            <HintPath>..\Libs\Microsoft.Extensions.DependencyInjection.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
