<Project>
    <!-- Language Metadata -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>

    <!-- Assembly Metadata -->
    <PropertyGroup>
        <Authors>SirRandoo</Authors>
        <Product>ToolkitUtils</Product>
        <RepositoryType>git</RepositoryType>
        <RootNamespace>SirRandoo.$(MsBuildProjectName)</RootNamespace>
        <InformationalVersion>7.0.6.0-RC1</InformationalVersion>
        <RepositoryUrl>https://github.com/sirrandoo/toolkit-utils</RepositoryUrl>
        <Copyright>AGPL3 Copyright (c) $([System.DateTime]::Now.ToString("yyyy")) SirRandoo</Copyright>
    </PropertyGroup>

    <!-- Build Metadata -->
    <PropertyGroup>
        <RimWorldVersion>1.6</RimWorldVersion>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <!-- Steam Paths -->
    <PropertyGroup>
        <MainWorkshopRoot>C:\Program Files (x86)\Steam\steamapps\workshop\content\294100</MainWorkshopRoot>
        <AltWorkshopRoot>D:\SteamLibrary\steamapps\workshop\content\294100</AltWorkshopRoot>

        <RimWorldWorkshopRoot Condition="Exists('$(MainWorkshopRoot)')">$(MainWorkshopRoot)</RimWorldWorkshopRoot>
        <RimWorldWorkshopRoot Condition="Exists('$(AltWorkshopRoot)')">$(AltWorkshopRoot)</RimWorldWorkshopRoot>
    </PropertyGroup></Project>
