<Project>
    <Import Project="ProductInformation.props" Condition="'$(UsingMicrosoftNoTargetsSdk)' != 'true'"/>

    <!-- Language metadata properties -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>

    <!-- Plugin properties -->
    <PropertyGroup>
        <PluginPrefix>$(SolutionName).Plugin.</PluginPrefix>
        <PaddedPluginPrefix>_$(PluginPrefix)</PaddedPluginPrefix>
        <IsCompatibilityPlugin>$(MSBuildProjectName.Contains('Plugin'))</IsCompatibilityPlugin>
        <PluginName Condition="$(IsCompatibilityPlugin)">$(MSBuildProjectName.Substring($(PaddedPluginPrefix.Length)))</PluginName>
    </PropertyGroup>

    <!-- Steam Paths -->
    <PropertyGroup>
        <MainWorkshopRoot>C:/Program Files (x86)/Steam/steamapps/workshop/content/294100</MainWorkshopRoot>

        <RimWorldWorkshopRoot Condition="Exists('$(MainWorkshopRoot)')">$(MainWorkshopRoot)</RimWorldWorkshopRoot>
    </PropertyGroup>
</Project>