<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Title>ToolkitUtils.Api</Title>
        <Description>The api for ToolkitUtils, an addon for the RimWorld mod "Twitch Toolkit."</Description>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NLog"/>
        <PackageReference Include="Lib.Harmony"/>
        <PackageReference Include="Mono.Reflection"/>
        <PackageReference Include="Samboy063.Tomlet"/>
        <PackageReference Include="com.sirrandoo.twitchtoolkit.ref"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ToolkitUtils.Mod\ToolkitUtils.Mod.csproj"/>
    </ItemGroup>
</Project>
