// Copyright (C) 2025 sirrandoo
// 
// This file is part of ToolkitUtils.
// 
// ToolkitUtils is free software: you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License version 3 as published by the
// Free Software Foundation.
// 
// ToolkitUtils is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
// for more details.
// 
// You should have received a copy of the GNU Lesser General Public License along
// with ToolkitUtils.Mod. If not, see <https://www.gnu.org/licenses/>.
using System;
using NetEscapades.EnumGenerators;

namespace ToolkitUtils.Mod.Presentation;

/// <summary>The various orders data can be ordered.</summary>
[EnumExtensions]
public enum SortOrder
{
    /// <summary>The given data has no sort order.</summary>
    None,

    /// <summary>The given data is sorted in ascending order by a given value.</summary>
    Ascending,

    /// <summary>The given data is sorted in descending order by a given value.</summary>
    Descending,
}

/// <summary>A collection of more extension methods for <see cref="SortOrder" />.</summary>
/// <remarks>
///     This class houses extension methods that aren't automatically generated by the
///     <see cref="EnumExtensionsAttribute" />'s associated source generator.
/// </remarks>
public static partial class SortOrderExtensions
{
    /// <summary>Returns the inverse of the current sort order.</summary>
    /// <param name="order">The current sort order being used by a user interface.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    ///     Raised when the sort order given isn't either
    ///     <see cref="SortOrder.None" />, <see cref="SortOrder.Ascending" />, or <see cref="SortOrder.Descending" />.
    /// </exception>
    /// <remarks>
    ///     This method is used to flip a user interface element's sort order between <see cref="SortOrder.Ascending" />
    ///     and <see cref="SortOrder.Descending" />. Should the order be <see cref="SortOrder.None" />, the method will instead
    ///     return <see cref="SortOrder.Ascending" />.
    /// </remarks>
    public static SortOrder Invert(this SortOrder order)
    {
        return order switch
        {
            SortOrder.None       => SortOrder.Descending,
            SortOrder.Ascending  => SortOrder.Descending,
            SortOrder.Descending => SortOrder.Ascending,
            var _                => throw new ArgumentOutOfRangeException(nameof(order), $"An unsupported sort order of '{order.ToString()}' was specified."),
        };
    }
}
