<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <Content Include="../../Compatibility/Ideology/Common/**/*.*">
            <Link>Common/%(RecursiveDir)%(FileName)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="com.sirrandoo.twitchtoolkit.ref"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../ToolkitUtils.Api/ToolkitUtils.Api.csproj"/>
        <ProjectReference Include="../ToolkitUtils.Core/ToolkitUtils.Core.csproj"/>
        <ProjectReference Include="../ToolkitUtils.Interactions.Commands/ToolkitUtils.Interactions.Commands.csproj"/>
        <ProjectReference Include="..\ToolkitUtils.Mod\ToolkitUtils.Mod.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.Extensions.Logging.Abstractions">
            <HintPath>..\Libs\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
        </Reference>
        <Reference Include="Remora.Commands">
            <HintPath>..\Libs\Remora.Commands.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>